### ISSUE TITLE
Implement power-ups

### ISSUE THREAD

**Issue by jensenbradshaw** [ENG1-Team-29/Assessment-2#5]
Implement five special power ups that the player's boat can obtain on the journey (e.g. granting temporary immunity, repairing damages).

**Comment by uoy-jb2501** [comment]
The player can now pick up different power-ups that do different things. The framework is in place to add new abilities easily.

**Comment by uoy-jb2501** [comment]
- Five powerups have been implemented
  - Speed
  - Invincibility
  - Rapid Fire
  - Damage Buff
  - Starburst Fire
- Powerups are placed randomly across the map
